-- ============================================
-- Wire OpenPhone calls + Quo auto-sync to prospecting.leads
-- ============================================
-- David's backend lives in `prospecting.leads`. This migration:
--   1. Creates prospecting.lead_calls (one row per OpenPhone call event,
--      linked to the lead via lead_id)
--   2. Recreates the Quo auto-sync trigger on prospecting.leads so HOT
--      prospects flow into the iPhone Quo Contacts list automatically
--   3. Adds quo_contact_id column to prospecting.leads for trigger write-back
--
-- Trigger uses pg_net to fire async POST to
-- https://stiloaipartners.com/api/openphone/sync-from-supabase
-- with a shared bearer secret stored in private.app_secrets.

create extension if not exists pg_net with schema extensions;

-- 1. Adjacent calls table (David's leads table doesn't track per-call detail)
create table if not exists prospecting.lead_calls (
    id bigint generated by default as identity primary key,
    lead_id integer references prospecting.leads(id) on delete cascade,
    openphone_call_id text unique,
    direction text not null default 'outbound',
    outcome text,
    duration_seconds int,
    recording_url text,
    transcript text,
    transcript_summary text,
    notes text,
    from_number text,
    to_number text,
    logged_by text,
    called_at timestamptz not null default now(),
    raw_payload jsonb
);
create index if not exists lead_calls_lead_idx
    on prospecting.lead_calls(lead_id, called_at desc);
create index if not exists lead_calls_outcome_idx
    on prospecting.lead_calls(outcome, called_at desc);

-- 2. quo_contact_id back-write column on leads
alter table prospecting.leads
    add column if not exists quo_contact_id text;

-- 3. Quo auto-sync trigger
create or replace function prospecting.sync_lead_to_quo()
returns trigger
language plpgsql
security definer
as $$
declare
    payload jsonb;
    secret  text;
    is_hot_now boolean;
    became_hot boolean;
    phone_changed boolean;
    profile_changed boolean;
begin
    -- David uses lowercase 'hot'/'warm'/'cold'. Be tolerant of either case.
    is_hot_now := lower(coalesce(NEW.tier, '')) = 'hot';
    became_hot := TG_OP = 'UPDATE'
                  AND lower(coalesce(OLD.tier, '')) IS DISTINCT FROM lower(coalesce(NEW.tier, ''))
                  AND lower(coalesce(NEW.tier, '')) = 'hot';
    phone_changed := TG_OP = 'UPDATE' AND COALESCE(OLD.owner_phone, OLD.phone) IS DISTINCT FROM COALESCE(NEW.owner_phone, NEW.phone);
    profile_changed := TG_OP = 'UPDATE'
                      AND (OLD.business_profile IS DISTINCT FROM NEW.business_profile
                           OR OLD.outreach_angle IS DISTINCT FROM NEW.outreach_angle
                           OR OLD.matched_product_name IS DISTINCT FROM NEW.matched_product_name);

    if COALESCE(NEW.owner_phone, NEW.phone) IS NULL then return NEW; end if;
    if NOT (
        (TG_OP = 'INSERT' AND is_hot_now)
        OR became_hot
        OR (is_hot_now AND TG_OP = 'UPDATE' AND (phone_changed OR profile_changed))
    ) then
        return NEW;
    end if;

    select value into secret from private.app_secrets where key = 'quo_sync_trigger';
    if secret IS NULL OR secret = '' then
        raise warning 'private.app_secrets[quo_sync_trigger] not set; skipping Quo sync for lead %', NEW.id;
        return NEW;
    end if;

    payload := jsonb_build_object(
        'type', TG_OP,
        'table', TG_TABLE_NAME,
        'record', to_jsonb(NEW)
    );

    perform net.http_post(
        url := 'https://stiloaipartners.com/api/openphone/sync-from-supabase',
        headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'Authorization', 'Bearer ' || secret
        ),
        body := payload,
        timeout_milliseconds := 5000
    );

    return NEW;
end;
$$;

drop trigger if exists trg_leads_quo_sync on prospecting.leads;
create trigger trg_leads_quo_sync
    after insert or update on prospecting.leads
    for each row execute function prospecting.sync_lead_to_quo();
