-- ============================================
-- Prospects shim: temporary CRM upstream for cold-call ops
-- ============================================
-- Stand-in for David's Python prospecting backend until his Cloud Run is live.
-- The Vercel routes under sites/stilo-ai/api/prospects/* fall back to reading
-- from these tables when env PROSPECTING_API_URL is empty or set to "local".
-- When David flips on, point PROSPECTING_API_URL at his service and the proxy
-- forwards instead. Keep these tables around as a safety net.
--
-- The shape mirrors the JSON contract the existing admin UI already consumes:
--   GET /api/prospects/callable     → { results: [...prospects] }
--   GET /api/prospects/{id}         → { ...prospect, call_history: [...] }
--   POST /api/prospects/{id}/log-call
--   GET /api/prospects/callbacks
--   GET /api/prospects/stats
--
-- Read by:
--   sites/stilo-ai/api/prospects/_shared.js (shim dispatcher)
--   sites/stilo-ai/api/openphone/webhook.js (call writes)
--
-- Run in Supabase SQL Editor against the stilo-ai-partners project.

create table if not exists public.prospects (
  id bigint generated by default as identity primary key,
  business_name text not null,
  owner_name text,
  owner_phone text,
  owner_phone_strict boolean not null default false,
  owner_email text,
  niche text,
  tier text not null default 'WARM',
  prospect_score int,
  talk_track text,
  recommended_product text,
  status text not null default 'callable',
  next_callback_at timestamptz,
  callback_reason text,
  last_called_at timestamptz,
  last_emailed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists prospects_status_idx on public.prospects(status);
create index if not exists prospects_phone_idx on public.prospects(owner_phone);
create index if not exists prospects_callback_idx on public.prospects(next_callback_at)
  where status = 'callback';

create table if not exists public.prospect_calls (
  id bigint generated by default as identity primary key,
  prospect_id bigint references public.prospects(id) on delete cascade,
  openphone_call_id text unique,
  direction text not null default 'outbound',
  outcome text,
  duration_seconds int,
  recording_url text,
  transcript text,
  transcript_summary text,
  notes text,
  from_number text,
  to_number text,
  logged_by text,
  called_at timestamptz not null default now(),
  raw_payload jsonb
);

create index if not exists prospect_calls_prospect_idx
  on public.prospect_calls(prospect_id, called_at desc);
create index if not exists prospect_calls_outcome_idx
  on public.prospect_calls(outcome, called_at desc);

alter table public.prospects enable row level security;
alter table public.prospect_calls enable row level security;

create policy "Admins read prospects" on public.prospects
  for select using (
    auth.jwt()->>'email' in (
      'remyleon11@gmail.com', 'stiloaiconsulting@gmail.com',
      'remyleon@stiloaipartners.com', 'davidcoira@stiloaipartners.com'
    )
  );
create policy "Admins write prospects" on public.prospects
  for all using (
    auth.jwt()->>'email' in (
      'remyleon11@gmail.com', 'stiloaiconsulting@gmail.com',
      'remyleon@stiloaipartners.com', 'davidcoira@stiloaipartners.com'
    )
  );
create policy "Admins read prospect_calls" on public.prospect_calls
  for select using (
    auth.jwt()->>'email' in (
      'remyleon11@gmail.com', 'stiloaiconsulting@gmail.com',
      'remyleon@stiloaipartners.com', 'davidcoira@stiloaipartners.com'
    )
  );
create policy "Admins write prospect_calls" on public.prospect_calls
  for all using (
    auth.jwt()->>'email' in (
      'remyleon11@gmail.com', 'stiloaiconsulting@gmail.com',
      'remyleon@stiloaipartners.com', 'davidcoira@stiloaipartners.com'
    )
  );

-- API routes use the service-role key so RLS is bypassed there. The policies
-- above guard direct REST queries from the browser if anyone connects via the
-- anon key.

-- ----------------------------------------------------------------
-- Seed: 6 demo prospects so today's smoke tests have something to call.
-- Replace the phone numbers with real lines you control before testing.
-- ----------------------------------------------------------------
insert into public.prospects (business_name, owner_name, owner_phone, owner_phone_strict, owner_email, niche, tier, prospect_score, talk_track, recommended_product)
values
  ('Bayside Auto Detailing', 'Carlos M.', '+13055550101', true, 'carlos@baysideauto.example', 'auto-services', 'HOT', 92,
   'They run paid ads on Instagram with no follow-up automation. Pitch ECHO + IGNITE: every missed call becomes a booked appointment.', 'ECHO + IGNITE'),
  ('Coral Gables Med Spa', 'Maria L.', '+17865550102', true, 'maria@coralgablesmedspa.example', 'med-spa', 'HOT', 88,
   'High-AOV service, Instagram-heavy, terrible Google rank. SCOUT for SEO + ECHO for after-hours booking.', 'SCOUT + ECHO'),
  ('South Beach Pizza Co', 'Tony R.', '+13055550103', false, 'tony@southbeachpizza.example', 'restaurant', 'WARM', 71,
   'Owner answers phone himself. Lead with FORGE (online ordering) since they''re losing volume to DoorDash.', 'FORGE'),
  ('Brickell Yoga Studio', 'Priya S.', '+17865550104', true, 'priya@brickellyoga.example', 'fitness', 'WARM', 68,
   'Heavy churn on memberships. REVIVE is the obvious win — automated win-back sequences.', 'REVIVE'),
  ('Doral Tax Pros', 'Anthony C.', '+13055550105', true, 'anthony@doraltaxpros.example', 'professional-services', 'COOL', 54,
   'Seasonal business so timing matters. Soft pitch ORACLE for client lifecycle insights.', 'ORACLE'),
  ('Wynwood HVAC', 'Janet F.', '+17865550106', false, 'janet@wynwoodhvac.example', 'home-services', 'WARM', 76,
   'Emergency calls go to voicemail after 6pm. ECHO is the killer pitch.', 'ECHO');
